CREATE TABLE CORRECTOR (ID INTEGER NOT NULL, APELLIDOS VARCHAR NOT NULL, CORREOELECTRONICO VARCHAR, MAXEXAMCORREGIR INTEGER, NOMBRE VARCHAR NOT NULL, TELEFONO VARCHAR, MATERIA INTEGER, PRIMARY KEY (ID))
CREATE TABLE MATERIA (ID INTEGER NOT NULL, ANIO INTEGER NOT NULL, NOMBRE VARCHAR NOT NULL, PRIMARY KEY (ID))
ALTER TABLE CORRECTOR ADD CONSTRAINT FK_CORRECTOR_MATERIA FOREIGN KEY (MATERIA) REFERENCES MATERIA (ID)
